addons:
  apt:
    packages:
    - openjdk-6-jdk
after_success:
- mvn clean test jacoco:report coveralls:report -Ptravis-jacoco
before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  -P ./target
- unzip -qq ./target/apache-maven-3.2.5-bin.zip -d ./target
- export M2_HOME=$PWD/target/apache-maven-3.2.5
- export PATH=$M2_HOME/bin:$PATH
jdk:
- oraclejdk8
language: java
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- mvn
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
sudo: false
